mavros_router:
  ros__parameters: {}

mavros_node:
  ros__parameters:
    fcu_url: udp://:14551@ # For use on Raspberry Pi, use /dev/serial0:921600. For use with PX4, use udp://:14540@
    gcs_url: ""
    tgt_system: 1

mavros:
  ros__parameters:
    plugin_allowlist:
      - sys_status
      - sys_time
      - vfr_hud
      - global_position
      - imu
      - wind_estimation
      - rc_io
      - command
      - waypoint
      - param
      - ftp
      - rpm

mavros/odometry:
  ros__parameters:
    fcu:
      odom_child_id_des: base_link
      odom_parent_id_des: map
    use_sim_time: false
